apiVersion: v1
kind: Service
metadata:
  name: db-service
  labels:
    name: db-service
    app: demo-voting-app

spec:
  ports:
    - port: 5432 # service port
      targetPort: 5432

  selector: # labels of pod
    name: postgres-pod
    app: demo-voting-app 

