apiVersion: v1
kind: Service
metadata:
  name: result-service
  labels:
    name: result-service
    app: demo-voting-app

spec:
  type: LoadBalancer
  ports:
    - port: 80 # service port
      targetPort: 80

  selector: # labels of pod
    name: result-app-pod
    app: demo-voting-app

