apiVersion: v1
kind: Service
metadata:
  name: voting-service
  labels:
    name: voting-service
    app: demo-voting-app

spec:
  type: LoadBalancer
  ports:
    - port: 80 # service port
      targetPort: 80

  selector: # labels of pod
    name: voting-app-pod
    app: demo-voting-app

