apiVersion: v1
kind: ReplicationController
metadata:
  name: myapp-rc
  labels:
    app: myapp-rc
    type: backend-test
spec:
  replicas: 3
  template: 
    metadata:
      name: myapp-pod
      labels:
        app: myapp
        type: backend-test
    spec:
      containers:
        - name: nginx-container
          image: nginx
  
  